### PR TITLE
add render_json method

### LINKED ISSUE #40: render_json: add function to render collapsible JSON in a notebook
function:

```
import json
from IPython.display import HTML

def render_json(jstr):
  if type(jstr) != str:
    jstr = json.dumps(jstr)
  return HTML("""
<script src="https://rawgit.com/caldwell/renderjson/master/renderjson.js"></script>
<script>
renderjson.set_show_to_level(1)
document.body.appendChild(renderjson(%s))
new ResizeObserver(google.colab.output.resizeIframeToContent).observe(document.body)
</script>
""" % jstr)
```

usage:

```
render_json("""{"example_array": [1,2,3], "example_object": {"a": 1, "b":2}}""")

⊖{
    "example_array": ⊕[3 items],
    "example_object": ⊕{2 items}
}
```

### PR DESCRIPTION
**Pull request by duncandewhurst**
Closes #40 

https://rawgit.com/ will soon be shut down, so I included https://rawgit.com/caldwell/renderjson/master/renderjson.js in this repo. I'm wondering if there's a better place to put it though, as the method won't work until this PR is merged. Also, it probably doesn't make sense to install it in the package installed by users if it will be fetched remotely.

### CODE REVIEW

**Comment by jpmckinney** [comment]
I used https://www.jsdelivr.com/rawgit with the rawgit URL to generate: https://cdn.jsdelivr.net/gh/caldwell/renderjson@master/renderjson.js

**Comment by duncandewhurst** [comment]
Great, thanks!

**Comment by duncandewhurst** [comment]
@jpmckinney this is ready for your review. I made a [notebook](https://colab.research.google.com/drive/1HRLBSzTilovxjChv728IXA8quJ5VcIOb) that you can use to test it.

**Comment by jpmckinney** [comment]
0.3.5 is released 🎉

**Pull request merged**
