### PR TITLE
Analyst dev

### PR DESCRIPTION
**Pull request by pindec**

### CODE REVIEW

**Comment by odscjames** [comment]
Talked to @kindly , we are happy to merge.

**Comment by odscjames** [comment]
Deliberately NOT deleting the branch, as some existing workbooks rely on it

**Comment by jpmckinney** [comment]
Can the workbooks be updated to use master?

**Comment by duncandewhurst** [comment]
Very few notebooks have been shared externally, but many have been created for internal use which would be time consuming to go through and update as Google Drive search doesn't allow you to filter on type:Colaboratory nor does it support text search within notebooks.

I suggest we:

1. Update the code in any notebooks filed in [4. Internal Resources](https://drive.google.com/drive/folders/0B79uNIOfT24eNVB1b1FhODZzYlE?usp=sharing), [4.5 Process Documentation](https://drive.google.com/drive/folders/1m97CRYyGeBAObJeb1_MXACxf5fLAHOQY?usp=sharing) and [3. Training Resources](https://drive.google.com/drive/folders/0B_hfAR6BAnvYWTlHWFVndkdnRWc?usp=sharing)

2. Send a message to 'Helpdesk teams' + Camila in the CRM to notify them of the change.

**Comment by jpmckinney** [comment]
I can search for:

    type:application/vnd.google.colaboratory "analyst-dev"

There are a lot of matches, but I think we can just focus on those in the above folders. The search seems to fail if combined with a `parent` filter, however.

**Comment by mrshll1001** [comment]
Found 1 Colab notebook in [Training Resources](https://drive.google.com/drive/folders/0B_hfAR6BAnvYWTlHWFVndkdnRWc?usp=sharing) ([2019-06 Data use training](https://colab.research.google.com/drive/1Ct-hnwbpH_K5UZ44QkK25ufsaDZFvyJW#scrollTo=a8tVaTr9KZIc)) and updated it. Moving onto the other folders now.

**Comment by mrshll1001** [comment]
In [4.5 Process documentation](https://drive.google.com/drive/folders/1m97CRYyGeBAObJeb1_MXACxf5fLAHOQY?usp=sharing)

The [2019 Data feedback colab](https://colab.research.google.com/drive/1Q1L4uZYYGFyj_pGkot5LipxMrgzeJvuy) had already been updated to master

The [Co-lab data feedback report generator (not for use)](https://colab.research.google.com/drive/1FuXbAAdWGouFZWJQRpRwSbEsZhGEIqjZ) didn't have any instances of analyst-dev.

**Comment by mrshll1001** [comment]
In [4 Internal Resources](https://drive.google.com/drive/folders/0B79uNIOfT24eNVB1b1FhODZzYlE)

Updated to use master
* [Usability Checks queries (draft)](https://colab.research.google.com/drive/1z9XiExYU9of1zY3j1BGdtP-HzrKds8yD#scrollTo=vPlYEfR9LCJq)
* [2019-03 new kingfisher views MEL](https://colab.research.google.com/drive/1L3Ou6_pTNHSgSuXcolquZdjfm3X9ja36#scrollTo=hXqst78xo0vx)
* [2019-01 Kingfisher to Google Sheets Exporter](https://colab.research.google.com/drive/1vDeV9B3NYv0EpfZ00SWJXMWxWs-WhlEb#scrollTo=--8vgOiP_58f)
* 


Didn't have references to analyst dev:
* [Proposed new MEL indicators](https://colab.research.google.com/drive/1hZaFm-1qS7zp8bDkj-OUUvp903TjRRwL)
* [(Romina) Proposed new MEL indicators](https://colab.research.google.com/drive/1NrZms2Vah8jG7ALLln8TWCiKgX_ayywK)
* [MAPS Quantitative Indicators](https://colab.research.google.com/drive/1xbqHel6s-z-fcwyFCQ4IWK-1iG_5RNyh)
* [UKRAINE MAPS indicators](https://colab.research.google.com/drive/1UVBeMI_qVkpbvyETzzIlGAkY4b-FYlhc)
* [PARAGUAY MAPS indicators (shared)](https://colab.research.google.com/drive/1InZ7_QY5NymYWfTB-52z8umKJDFWZ52g)
* [PARAGUAY MAPS indicators](https://colab.research.google.com/drive/1LSFen7gqPX61e0rfd58eJaQ9FdBHM4aR)
* [GPA reporting: Australia's data exploration](https://colab.research.google.com/drive/1w-5DtCn-DnLeOZvzKgj_5ZUxXI4Ok5m-)
* [GPA reporting with OCDS: Data exploration of Candidate Countries (draft)](https://colab.research.google.com/drive/18iSUqJwFEr7cJvvHsrJdVor0tvuEU3We)
* [GPA reporting with OCDS: Australia (draft)](https://colab.research.google.com/drive/1qAg8JkmsBDYg6Ik2YMRF8wMn9sJUvUIK)
* [Copy of 2019-01 Kingfisher to google sheets exporter](https://colab.research.google.com/drive/1c-maNKzq9QBwPtOQRJYsYHPdpDWN0HkK#scrollTo=72kzgcM4FhMY)
* [2019-02 OCDS CSV file to OCDS JSON Exporter](https://colab.research.google.com/drive/1wzSt-XnE0lrSgaFYyTTFuBj2YTt1EA2k)
* [2019-09 Coverage Visualization](https://colab.research.google.com/drive/1WVNRtBciCvIbo1Yn2gvsgS-8TVpGHcha)
* [2019-01 Coverage Visualization](https://colab.research.google.com/drive/1sMktugIqkNJvF5Yg-d01J1e2eKDTQv1j)
* [2019-06 Chile Red Flags Event](https://colab.research.google.com/drive/14dEKETVg0FdkJjNdmRFfdX6ceLuhAWVc)


There were a few in [Jupyter Notebooks/_Archive](https://drive.google.com/drive/folders/1rEOe4fDzEcEy6kL1TG4efYp1edtZUmqc) that I didn't touch because of the archived nature. Happy to look at these too if needs be.

**Comment by duncandewhurst** [comment]
Thanks @mrshll1001!

I've sent the CRM message and asked @yolile to confirm whether any publishers are using notebooks that use the `analyst-dev` branch.

**Pull request merged**
